export const SPELL_ATTRIBUTE = {
    AntiGravity: 'Anti Gravity',
    Asteroid: 'Asteroid',
    BigBang: 'Big Bang',
    CerberusFlame: 'Cerberus Flame',
    ChainLightning: 'Chain Lightning',
    ChargedParticle: 'Charged Particle',
    Conflagration: 'Conflagration',
    Constellation: 'Constellation',
    Crater: 'Crater',
    DestructionField: 'Destruction Field',
    DisintegrationRay: 'Disintegration Ray',
    Doppelganger: 'Doppelganger',
    Earthquake: 'Earthquake',
    ElectricOrb: 'ElectricOrb',
    ElectricityBlast: 'Electricity Blast',
    ElectromagneticBurst: 'Electromagnetic Burst',
    Emp: 'Emp',
    ExtremeWeather: 'Extreme Weather',
    Familiar: 'Familiar',
    FireAtWill: 'Fire At Will',
    FireAura: 'Fire Aura',
    Fireworks: 'Fireworks',
    Flamestrike: 'Flamestrike',
    Flare: 'Flare',
    GreatEruption: 'Great Eruption',
    IceAge: 'IceAge',
    Judgment: 'Judgment',
    LightningExplosion: 'Lightning Explosion',
    MagicArrow: 'Magic Arrow',
    MagicBlade: 'Magic Blade',
    MagicMissile: 'Magic Missile',
    MagmaEruption: 'Magma Eruption',
    Melt: 'Melt',
    MeteorShower: 'Meteor Shower',
    NuclearFusion: 'Nuclear Fusion',
    Pyromaniac: 'Pyromaniac',
    Ragnarok: 'Ragnarok',
    Rapture: 'Rapture',
    Reflect: 'Reflect',
    SatansNails: 'Satans Nails',
    ShootingStar: 'Shooting Star',
    SirensSong: 'Sirens Song',
    Spark: 'Spark',
    SubZero: 'Sub Zero',
    Superconductivity: 'Superconductivity',
    Thunderclap: 'Thunderclap',
    ToxicGaz: 'Toxic Gaz',
    VolcanicEruption: 'Volcanic Eruption',
    Void: 'Void',
    Wipeout: 'Wipeout',
    WillOTheWisp: 'Will O\' The Wisp',
} as const;


// Derive types from runtime objects
export type SpellAttribute = typeof SPELL_ATTRIBUTE[keyof typeof SPELL_ATTRIBUTE];

// Helper types for arrays of all values
export type SpellAttributeValues = typeof SPELL_ATTRIBUTE;