export const SPELL_ATTRIBUTE = {
    AntiGravity: 'AntiGravity',
    Asteroid: 'Asteroid',
    BigBang: 'BigBang',
    CerberusFlame: 'CerberusFlame',
    ChainLightning: 'ChainLightning',
    ChargedParticle: 'ChargedParticle',
    Conflagration: 'Conflagration',
    Constellation: 'Constellation',
    Crater: 'Crater',
    DestructionField: 'DestructionField',
    DisintegrationRay: 'DisintegrationRay',
    Doppelganger: 'Doppelganger',
    Earthquake: 'Earthquake',
    ElectricOrb: 'ElectricOrb',
    ElectricityBlast: 'ElectricityBlast',
    ElectromagneticBurst: 'ElectromagneticBurst',
    Emp: 'Emp',
    ExtremeWeather: 'ExtremeWeather',
    Familiar: 'Familiar',
    FireAtWill: 'FireAtWill',
    FireAura: 'FireAura',
    Fireworks: 'Fireworks',
    Flamestrike: 'Flamestrike',
    Flare: 'Flare',
    GreatEruption: 'GreatEruption',
    IceAge: 'IceAge',
    Judgment: 'Judgment',
    LightningExplosion: 'LightningExplosion',
    MagicArrow: 'MagicArrow',
    MagicBlade: 'MagicBlade',
    MagicMissile: 'MagicMissile',
    MagmaEruption: 'MagmaEruption',
    Melt: 'Melt',
    MeteorShower: 'MeteorShower',
    NuclearFusion: 'NuclearFusion',
    Pyromaniac: 'Pyromaniac',
    Ragnarok: 'Ragnarok',
    Rapture: 'Rapture',
    Reflect: 'Reflect',
    SatansNails: 'SatansNails',
    ShootingStar: 'ShootingStar',
    SirensSong: 'SirensSong',
    Spark: 'Spark',
    SubZero: 'SubZero',
    Superconductivity: 'Superconductivity',
    Thunderclap: 'Thunderclap',
    ToxicGaz: 'ToxicGaz',
    VolcanicEruption: 'VolcanicEruption',
    Void: 'Void',
    Wipeout: 'Wipeout',
    WillOTheWisp: 'WillOTheWisp',
} as const;


// Derive types from runtime objects
export type SpellAttribute = typeof SPELL_ATTRIBUTE[keyof typeof SPELL_ATTRIBUTE];

// Helper types for arrays of all values
export type SpellAttributeValues = typeof SPELL_ATTRIBUTE;